### ISSUE TITLE
Turkish dictionary

### ISSUE THREAD

**Issue by Sadi58** [kwonoj/hunspell-dict#11]
The source URL https://tr-spell.googlecode.com no longer exists.
Does Turkish dictionary have a maintainer?

**Comment by kwonoj** [comment]
I can't say for sure, I don't manage dict directly and that url was source at the moment. If it's gone, likely possible I don't have update source.

**Comment by Sadi58** [comment]
**Sources** with possible dates of last dictionary update: 
2006 - https://cgit.freedesktop.org/libreoffice/dictionaries/tree/tr_TR
2011 - https://addons.mozilla.org/en-US/firefox/addon/turkce-yazim-denetimi/
2014 - https://extensions.libreoffice.org/extensions/turkish-spellcheck-dictionary
2015 - https://addons.mozilla.org/en-US/firefox/addon/türkçe-imla-denetimi/
