### ISSUE TITLE
Character coding is not correct in Hungarian package(hu-hu) 

### ISSUE THREAD

**Issue by mucsi96** [kwonoj/hunspell-dict#7]
First of all thank you so much for publishing the dictionaries to NPM! That's an awesome idea!

Looks like it is not UTF-8

![screen shot 2017-11-06 at 11 31 24 pm](https://user-images.githubusercontent.com/3163392/32467366-adf4730c-c34a-11e7-9ff3-716f4559bdb5.png)

Do you have any idea what can be the issue?

**Comment by kwonoj** [comment]
🤔  interesting, I thought I correctly put utf-8 encoded dic files, not sure when / how did got there.

**Comment by kwonoj** [comment]
@mucsi96 is below correct encoding?

![image](https://user-images.githubusercontent.com/1210596/32468046-8ef60414-c301-11e7-8009-25bc3c60656f.png)

**Comment by kwonoj** [comment]
@mucsi96 I'm going to merge & bump https://github.com/kwonoj/hunspell-dict/pull/8 , please correct me if new dict's are still invalid.

**Comment by mucsi96** [comment]
@kwonoj Thank you for such fast response, fix and releases! You are awesome!
